spring:
  application:
    name : springboot3-modern-basics
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update   # Para desarrollo (en prod usa 'validate' o 'none')
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
